# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/B. Tech II year/CSN_221/Project/32-bit-MIPS-Processor-master/Modules/ALU Control Unit/ALUCU1/ALUCU1.cache/wt} [current_project]
set_property parent.project_path {E:/B. Tech II year/CSN_221/Project/32-bit-MIPS-Processor-master/Modules/ALU Control Unit/ALUCU1/ALUCU1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{E:/B. Tech II year/CSN_221/Project/32-bit-MIPS-Processor-master/Modules/ALU Control Unit/ALUCU1/ALUCU1.srcs/sources_1/new/ALU_CU.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ALU_CU -part xc7k70tfbv676-1


write_checkpoint -force -noxdef ALU_CU.dcp

catch { report_utilization -file ALU_CU_utilization_synth.rpt -pb ALU_CU_utilization_synth.pb }
